modLoader="kotlinforforge"
loaderVersion="[4,)"
license = "MIT"
[[mods]]
modId = "nishiki"
version = "${file.jarVersion}"
displayName = "Nishiki Finders"
authors="nin8995"
description = '''

'''
[[dependencies.nishiki]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nishiki]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
